[build]
publish = "dist"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-schedule"
[plugins.inputs]
functions = [
    { function = "today-game", schedule = "59 14 * * *" },
    { function = "today-game", schedule = "5 15 * * *" }
]