[build]
publish = "dist"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[[scheduled_functions]]
name = "today-game"
schedule = "55 14 * * *"

[[scheduled_functions]]
name = "today-game"
schedule = "5 15 * * *"
