[build]
publish = "dist"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[functions]
[[functions."today-game"]]
schedule = "55 14 * * *"

[[functions."today-game"]]
schedule = "5 15 * * *"
